[pytest]
DJANGO_SETTINGS_MODULE = service_booking_backend.settings
python_files = tests.py test_*.py *_tests.py
addopts = --ignore-glob='*/._*' --cov=bookings --cov=service_booking_backend --cov-report=term-missing
